### ISSUE TITLE
error running `acqf` in R colab

### ISSUE THREAD

**Issue by hududed** [mlr-org/mlr3mbo#101]
I am not sure if I should raise the issue here, but I need some info before raising it to `rpy2`.

But basically I intended to share a public notebook to run `mlr3mbo` on google colab, but come to this error when calling `acqf`:
```
RRuntimeError: Error in .subset2(x, "print")(...) : unused argument (useS4 = FALSE)
```

To reproduce, run all cells [here](https://colab.research.google.com/drive/18Sl-H7pCK1ReJ69TWywtQMGyk_JJitLf?usp=share_link).

Is this related to rpy2-r6 interface? or how to best debug?

**Comment by larskotthoff** [comment]
Sorry, this is completely unrelated to mlr3mbo and nothing that can be fixed in the package.
