### ISSUE TITLE
AcqF with param_set

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3mbo#3]
Currently AcqFuns can have `settings`. In our other packages these settings are always encoded in a ParamSet. So we should also follow that scheme here.
Problem: Nameclash wit the param_set of the AcqFunction that defines the search space.

**Comment by jakob-r** [comment]
First: We definetly want to have AcqF settings/param_sets
My suggestion: settings go into `param_set`. Domain goes into `domain_param_set`.
Why? Consistency with mlr3verse. The param_set controls how this object behaves.

**Comment by berndbischl** [comment]
> Problem: Nameclash wit the param_set of the AcqFunction that defines the search space.

thats not a problem? "settings" are still called "settings" but are not a list but a paramset?

**Comment by berndbischl** [comment]
also it might be that @mb706 already has some code for "functions with extra infos"

**Comment by jakob-r** [comment]
> thats not a problem? "settings" are still called "settings" but are not a list but a paramset?

But in the rest of mlr3verse settings are always called `param_set`. But it can stay with the name `settings`. Just wanted to mention this.

**Comment by berndbischl** [comment]
That's really just a convention. A ParamSet is a datatype. An object can have many members of that type. Under various names. I also discussed this with martin. That's really important to understand.

**Comment by jakob-r** [comment]
Obviously. But for the usability this convention might be important. This way I always now with what datatype I am dealing.

**Comment by berndbischl** [comment]
Can we please stop this discussion? You also don't argue to have always only one list-member in a class. And call it "list". This is the same situation.
