### ISSUE TITLE
SurrogateLearner `character` -> `factor` conversion

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3mbo#30]
When creating an mlr3 `Task`, we currently get `character` features for `ParamFct` params.
Currently does not happen automatically, which makes it impossible for some learners / encoders. 
Should this be done automatically?

**Comment by pfistfl** [comment]
This is basically a design philosophy question, that should also influence https://github.com/mlr-org/mlr3pipelines/issues/555

**Comment by pfistfl** [comment]
I implemented a stupid converter in #35, that for now autoconverts everything.

**Comment by sumny** [comment]
closed by #35
