### ISSUE TITLE
Encapsulate of SurrogateLearner

### ISSUE THREAD

**Issue by sumny** [mlr-org/mlr3mbo#33]
We may want to set encapsulate of `SurrogateLearner`s to `"evaluate`" and provide a stable fallback like ranger

**Comment by sumny** [comment]
see also #32

**Comment by sumny** [comment]
I guess we could also enforce this directly in the loops we provide e.g., `bayesop_soo.R`?

**Comment by pfistfl** [comment]
See whether `default_surrogate` handles this sufficiently 
https://github.com/mlr-org/mlr3mbo/pull/35/files#diff-3cbf17774e580bb4dd3dbe2eb34bb806f1021a211b036107137fc27d2ae504feR92
