### ISSUE TITLE
old mlrmbo default unavailable in mlr3

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3mbo#36]
The old `mlrMBO` default `lrn("regr.randomForest", se.method = "jackknife", keep.inbag = TRUE)` is not available in `mlr3` currently. jacknife estimation was implemented in `mlr` on top of RF back then,  and this has not been ported over.

Do we need this as a default or are we ok with `regr.ranger`?

**Comment by sumny** [comment]
I think you can also do `jackknife` se estimation in `ranger`?

**Comment by pfistfl** [comment]
Then let us perhaps verify, that this does the same as what we do in old mlr, and default to that.
