### ISSUE TITLE
Integrate focussearch as AcqOptimizer

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3mbo#4]
Probably the implementation should be in its own package.

**Comment by berndbischl** [comment]
it already is
https://github.com/berndbischl/focussearch

**Comment by berndbischl** [comment]
we are discussing a bit whether this really is the best optimizer we could use

**Comment by jakob-r** [comment]
Wether it is the best optimizer can be best found out with a benchmark after it has been integrated, right?

**Comment by berndbischl** [comment]
Well. I would rather implement just one optimizer not many. And a benchmark can be run through a simpler setup.

**Comment by jakob-r** [comment]
I think in the end we will likely need multiple optimizers unfortunately anyhow. But certainly we are better of to start with just one that works universally well. Which one do you have in mind?

**Comment by berndbischl** [comment]
I don't know exactly. Or at least I don't want to type all of this. We should probably integrate focus search now. But I would like to address this topic for a new version. We never did this properly

**Comment by sumny** [comment]
see mlr-org/bbotk#144
