### ISSUE TITLE
Document bb_optimize version

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3mbo#58]
We should better document that mlr3mbo can also be used for general purpose stuff using `bbotk::bb_optimize`.
Perhaps a small example in the readme is sufficient.

**Comment by sumny** [comment]
wait for https://github.com/mlr-org/bbotk/issues/169

**Comment by sumny** [comment]
closed by c6c74f6ada06dfe17fd9d458841b7023d19cc6bc
