### ISSUE TITLE
Simple example fails to execute

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3mbo#74]
### Description

The [simple tuning example](https://github.com/mlr-org/mlr3mbo#simple-tuning-example-using-defaults) doesn't work?

### Reproducible example

``` r
set.seed(1)
library(mlr3)
library(mlr3tuning)
#> Loading required package: paradox
library(mlr3mbo)

task = tsk("pima")

learner = lrn("classif.rpart", cp = to_tune(lower = 1e-04, upper = 1e-1, logscale = TRUE))

instance = tune(
  method = "mbo",
  task = task,
  learner = learner,
  resampling = rsmp("holdout"),
  measure = msr("classif.ce"),
  term_evals = 10
)
#> INFO  [09:48:29.960] [bbotk] Starting to optimize 1 parameter(s) with '<OptimizerMbo>' and '<TerminatorEvals> [n_evals=10, k=0]'
#> Error: Element with key 'regr.km' not found in DictionaryLearner! Did you mean 'regr.debug' / 'regr.featureless' / 'regr.rpart'?

instance$result
#> Error in eval(expr, envir, enclos): object 'instance' not found
```

<sup>Created on 2022-07-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sumny** [comment]
Hi, i think I failed to include the packages required from the example above the tuning example, especially `mlr3learners` for the GP.

Maybe try

```
library(mlr3learners)
```

And then the example should work!

**Comment by sumny** [comment]
Also make sure to actually have `DiceKriging` installed due to using a GP as surrogate here

**Comment by bblodfon** [comment]
True! `library(mlr3learners)` and `DiceKriging` were both needed!
